### ISSUE TITLE
No module named 'nn_core'

### ISSUE THREAD

**Issue by Mecel1147** [riccardomarin/NICP#12] opened 2024-12-16 02:28 UTC
Hi，
when I run `./src/lvd_templ/evaluation/evaluation_benchmark.py`，
I got an error:
```
  /home/shao/.conda/envs/nsr/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py:68: DeprecationWarning: `TorchScript` support for functional optimizers is deprecated and will be removed in a future PyTorch release. Consider using the `torch.compile` optimizer instead.
    from torch.distributed.optim import DistributedOptimizer
  Traceback (most recent call last):
    File "./src/lvd_templ/evaluation/evaluation_benchmark.py", line 18, in <module>
      from nn_core.common import PROJECT_ROOT
  ModuleNotFoundError: No module named 'nn_core'```

can you help me with it?
Thanks.

**Comment by riccardomarin** [comment] 2024-12-18 11:34
Hi @Mecel1147 ,
Thank you for reaching out; this seems a duplicate of #8.

 Feel free to reopen the issue if the problem persists.

**Closed as completed by riccardomarin** 2024-12-18 11:34 UTC

**Comment by Mecel1147** [comment] 2024-12-20 09:17
Thank you.
I have fixed this problem.
